### ISSUE TITLE
Using removed Babel 5 option

### ISSUE THREAD

**Issue by svenadlung** [FormidableLabs/component-playground#56]
After cloning the repo, "npm install" and "npm run dev" I get the following error:
`ERROR in ./demo/app.jsx
Module build failed: ReferenceError: [BABEL] /Users/x/Websites/component-playground/demo/app.jsx: Using removed Babel 5 option: base.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
    at Logger.error (/Users/x/Websites/component-playground/node_modules/babel-core/lib/transformation/file/logger.js:39:11)
    at OptionManager.mergeOptions (/Users/x/Websites/component-playground/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:20)
    at OptionManager.init (/Users/x/Websites/component-playground/node_modules/babel-core/lib/transformation/file/options/option-manager.js:465:10)
    at File.initOptions (/Users/x/Websites/component-playground/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File (/Users/x/Websites/component-playground/node_modules/babel-core/lib/transformation/file/index.js:123:22)
    at Pipeline.transform (/Users/x/Websites/component-playground/node_modules/babel-core/lib/transformation/pipeline.js:45:16)
    at transpile (/Users/x/Websites/component-playground/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/x/Websites/component-playground/node_modules/babel-loader/index.js:88:12)
 @ multi app
`

Is this a known issue?

**Comment by svenadlung** [comment]
Fixing the webpack config as described in #55 worked. Thanks a lot!
Unfortunately page is loading with errors. Console in Chrome:
`Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Index`.warning @ main.js:2258
main.js:1181 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `Index`.`

**Comment by kenwheeler** [comment]
Should be all set
